name: PublishDryRun

on:
  push:
    branches:
      - master
# on:
#   workflow_dispatch

jobs:
  publishdryrun:
    name: Publish Dry Run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - riscv32imc-esp-espidf
          - xtensa-esp32-espidf
          - xtensa-esp32s2-espidf
          - xtensa-esp32s3-espidf

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2

      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          default: true
          toolchain: nightly
          components: rustfmt, clippy
        if: matrix.target == 'riscv32imc-esp-espidf'

      - name: Setup | Std
        run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
        if: matrix.target == 'riscv32imc-esp-espidf'

      - name: Install Rust for Xtensa
        uses: esp-rs/xtensa-toolchain@v1.2.0
        with:
          default: true
        if: matrix.target != 'riscv32imc-esp-espidf'

      - name: Build | Publish Dry Run
        run: cargo publish --dry-run --target ${{ matrix.target }} -Zbuild-std=std,panic_abort -Zbuild-std-features=panic_immediate_abort
        env:
          ESP_IDF_TOOLS_INSTALL_DIR: out
